### ISSUE TITLE
Memory requirement in 

### ISSUE THREAD

**Issue by bangawayoo** [maximilianmozes/fgws#2]
Hi,
I had a question regarding the use of word embedding in the DataModule. 
When initializing the DataModule and populating the word embedding, I run into a out of memory error on a 32GB RAM machine. Do you have an estimate of how much memory is needed to run `detect.py` script? Or how large was the RAM on your machine? 

Thanks in advance!

**Comment by maximilianmozes** [comment]
Hi, I'm afraid 32GB RAM might not be enough for this. I ran the script on a 128GB RAM machine and was able to execute multiple experiments at the same time. The saved word embeddings file is around 26GB in size.
